"""Add OSM fields to services

Revision ID: 98fa2de67966
Revises: 2a6ec55b64cd
Create Date: 2026-08-26 08:37:59.301508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fa2de67966'
down_revision = '2a6ec55b64cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osm_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('osm_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('osm_type')
        batch_op.drop_column('osm_id')

    # ### end Alembic commands ###
