"""add notes and favorites to saved services

Revision ID: a2d65eac24c0
Revises: 0f04353acd68
Create Date: 2026-08-28 10:03:18.738724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d65eac24c0'
down_revision = '0f04353acd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_services', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')
        batch_op.drop_column('note')

    # ### end Alembic commands ###
